### PR TITLE
add support for active and fail offsets

### PR DESCRIPTION
**Pull request by jacobmolby**
Adds support for providing active and fail offsets to the gesture.

Very useful when used inside other GestureHandlers or scrollable containers.

### CODE REVIEW

**Comment by jacobmolby** [comment]
@alantoa Have you had a chance to look at this? :)

**Comment by jacobmolby** [comment]
@alantoa ? :)

**Comment by alantoa** [comment]
Hey @jacobmolby, I apologize for the delayed response as I was busy. I'll take a look and test it today, but currently it looks good to me.

**Comment by jacobmolby** [comment]
Thanks, no worries. It's much easier to see the changes with "hide whitespace": 
image

**Comment by alantoa** [comment]
@jacobmolby LGTM, thanks! just released it in [v2.4.7 ](https://github.com/alantoa/react-native-awesome-slider/releases/tag/v2.4.7)

**Pull request merged**
